spring:
  datasource:
    url: jdbc:mysql://localhost:3306/embracon?useSSL=false&serverTimezone=UTC
    username: embracon
    password: embracon2319!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: false
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, beans
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
